// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFq1lfVLbxvqEvOO20X30K0nBokgdskUs',
    appId: '1:273461745269:web:ac361ee5a5205fc3c50a3c',
    messagingSenderId: '273461745269',
    projectId: 'bigfoot-97107',
    authDomain: 'bigfoot-97107.firebaseapp.com',
    storageBucket: 'bigfoot-97107.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMjllO7HYpP-IYiRonof_dDNAWeTaGXRQ',
    appId: '1:273461745269:android:8b0b02f93b08d34ac50a3c',
    messagingSenderId: '273461745269',
    projectId: 'bigfoot-97107',
    storageBucket: 'bigfoot-97107.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPsFtpGMPyJYFPyNlg7h81zazRXVdzC-A',
    appId: '1:273461745269:ios:df83dafee08de068c50a3c',
    messagingSenderId: '273461745269',
    projectId: 'bigfoot-97107',
    storageBucket: 'bigfoot-97107.appspot.com',
    iosClientId: '273461745269-viqu1a1datorpkjvm7r6dgatuesuus02.apps.googleusercontent.com',
    iosBundleId: 'com.example.bigfootDashboard',
  );
}
